#ifndef _Constantes_H_
#define _Constantes_H_

#define NOMBRE_JUEGO "SnowBross V1"

#define PI 3.141592654f

// Modelos de figuras
#define CIRCULO "circulo"
#define RECTANGULO "rectangulo"
#define TRIANGULO "triangulo"
#define CUADRADO "cuadrado"
#define PENTAGONO "pentagono"
#define HEXAGONO "hexagono"
#define PARALELOGRAMO "hexagono"

enum TIPO_FIGURA {
			TIPO_CIRCULO = 1,
			TIPO_RECTANGULO,
			TIPO_POLIGONO,
			TIPO_TRIANGULO,
			TIPO_CUADRADO,
			TIPO_PENTAGONO,
			TIPO_HEXAGONO,
			TIPO_PARALELOGRAMO,
			TIPO_TRAPECIO,
			TIPO_SNOWBOY,
			TIPO_NIEVE,
			TIPO_ENEMIGO,
			//Tipo enemigo se podria reemplazar por TIPO_ENEMIGO_ESTANDAR y TIPO_ENEMIGO_TIRA_FUEGO
			//TIPO_ENEMIGO_BOLA_DE_NIEVE,
			TIPO_NULL
					};




#define LADOS_TRIANGULO 3
#define LADOS_CUADRADO 4
#define LADOS_PENTAGONO 5
#define LADOS_HEXAGONO 6
#define LADOS_PARALELOGRAMO 4
#define LADOS_TRAPECIO 4
#define MAX_LADOS 6 // El poligono de mayor lados


// Defaults
#define PATH_ESCENARIO_DEFAULT "config\\escenario_default.json"
#define EXTENSION ".json"

#define FPS 30

#define ALTO_DEFAULT_PX 600
#define ANCHO_DEFAULT_PX 800
#define ALTO_DEFAULT_UL 100
#define ANCHO_DEFAULT_UL 100

// Definicion de eventos recibidos por la vista (cliente)
#define EVENTO_CREAR_ESCENARIO_1 100

#define EVENTO_CREAR_CIRCULO 200
#define EVENTO_CREAR_TRIANGULO 201
#define EVENTO_CREAR_RECTANGULO 202
#define EVENTO_CREAR_PENTAGONO 203
#define EVENTO_CREAR_HEXAGONO 203

#define EVENTO_ACTUALIZAR_FIGURA 300

//Simulacion del paso del tiempo Box2D
const float PASO_TIEMPO = 1.0f / 60.0f;
const int ITERACION_VELOCIDAD = 3;
const int ITERACION_POSICION = 2;

//gravedad del mundo Box2D
const float GRAVEDAD_X = 0.0f;
const float GRAVEDAD_Y = -10.0f;

#define SNOWBOY_CONSTANTE_DESACELERACION 0.5

enum EVENTOS_RECIBIDOS_CLIENTE { 
					EVENTO_CLIENTE_JUEGO_RESET = 0,
					EVENTO_CLIENTE_JUEGO_PAUSA,
					EVENTO_CLIENTE_JUEGO_STEP,
					EVENTO_CLIENTE_FIGURA_ACTUALIZAR,
					EVENTO_CLIENTE_PERSONAJE_NUEVO_ID,
					EVENTO_CLIENTE_PERSONAJE_CREADO, 

					//EVENTO_CLIENTE_PERSONAJE_QUIETO, 
					EVENTO_CLIENTE_PERSONAJE_QUIETO_IZQ,
					EVENTO_CLIENTE_PERSONAJE_QUIETO_DER,

					//EVENTO_CLIENTE_PERSONAJE_CAMINANDO, 
					EVENTO_CLIENTE_PERSONAJE_CAMINANDO_IZQ,
					EVENTO_CLIENTE_PERSONAJE_CAMINANDO_DER,

					//EVENTO_CLIENTE_PERSONAJE_SALTANDO, 
					EVENTO_CLIENTE_PERSONAJE_SALTANDO_IZQ, 
					EVENTO_CLIENTE_PERSONAJE_SALTANDO_DER,
 
					EVENTO_CLIENTE_PERSONAJE_MURIENDO,
					EVENTO_CLIENTE_PERSONAJE_MUERTO,
					EVENTO_CLIENTE_PERSONAJE_LANZANDO,
					EVENTO_CLIENTE_PERSONAJE_EMPUJANDO,

					EVENTO_CLIENTE_CONEXION_ACEPTADA,
					EVENTO_CLIENTE_RECONEXION_ACEPTADA,
					EVENTO_CLIENTE_CONEXION_RECHAZADA_SALA_LLENA,
					EVENTO_CLIENTE_CONEXION_RECHAZADA_NOMBRE_EXISTENTE,

					//CTE DE ENEMIGO
					EVENTO_CLIENTE_ENEMIGO_BOLA_DE_NIEVE,
					EVENTO_CLIENTE_ENEMIGO_BOLA_DE_NIEVE_PATEADA,

					EVENTO_CLIENTE_SNOWBOY_ATRAPADO_EN_BOLA_DE_NIEVE,
					
					EVENTO_CLIENTE_ENEMIGO_MUERTO_POR_BOLA_DE_NIEVE_DESTRUIDA,
					EVENTO_CLIENTE_ENEMIGO_MUERTO_POR_GOLPE_DE_BOLA_DE_NIEVE


					};





#define SNOWBOY_ESCALA 1.2 

#define SNOWBOY_ALTO_PX 30
#define SNOWBOY_ANCHO_PX 20



#define RADIO_CUERPO  (1.3f*SNOWBOY_ESCALA)

#define SNOWBOY_FLOTACION_DESEADA (RADIO_CUERPO*2)//1.05F 

#define ALTURA_INICIAL_PIERNAS 0//(RADIO_CUERPO/-2)//-0.5f
#define ALTURA_FINAL_PIERNAS (-SNOWBOY_FLOTACION_DESEADA/*-0.5*/)//-2.0f
#define ANCHO_PIERNAS (RADIO_CUERPO/4)

#define ANGULO_MAX_ESCALABLE 55

#define RAYO_HORIZONTAL_POSX (RADIO_CUERPO+0.3f)
#define RAYO_HORIZONTAL_POSY 0

#define VELOCIDAD_HORIZONTAL 10
#define VELOCIDAD_SALTO 10

#define SNOWBOY_ALTO_UL (SNOWBOY_FLOTACION_DESEADA+RADIO_CUERPO)
#define SNOWBOY_ANCHO_UL (RADIO_CUERPO*2)

#define SNOWBOY_DIFERENCIA_CENTRO_CUERPO_CENTRO_FIGURA (SNOWBOY_FLOTACION_DESEADA-SNOWBOY_ALTO_UL/2)








#endif