#ifndef _Constantes_H_
#define _Constantes_H_

#define NOMBRE_JUEGO "SnowBross V3"

#define SERVIDOR_PUERTO_DEFAULT 8200
#define CLIENTE_PUERTO_DEFAULT  8200

#define PI 3.141592654f

// Modelos de figuras
#define CIRCULO "circulo"
#define RECTANGULO "rect"
#define POLIGONO "poli"
#define TRIANGULO "triangulo"
#define CUADRADO "cuadrado"
#define PENTAGONO "pentagono"
#define HEXAGONO "hexagono"
#define PARALELOGRAMO "paralelogramo"
#define TRAPECIO "trapecio"
#define PROYECTIL "proyectil"

#define DIABLO "diablo"
#define DRAGON "dragon"
#define ENEMIGO "enemigo"
#define VELOCIDAD "velocidad"
#define VIDA "vida"

enum TIPO_FIGURA {
			TIPO_CIRCULO = 1,
			TIPO_RECTANGULO,
			TIPO_POLIGONO,
			TIPO_TRIANGULO,
			TIPO_CUADRADO,
			TIPO_PENTAGONO,
			TIPO_HEXAGONO,
			TIPO_PARALELOGRAMO,
			TIPO_TRAPECIO,
			TIPO_SNOWBOY,

			/*IMPORTANTE, CUANDO SE AGREGUE EL TIPO_DRAGON, VA A HABER QUE AGREGARLO
			  EN TODAS LAS COMPARACIONES EN LAS QUE SE HACE (tipo == TIPO_DIABLO)
			*/
			TIPO_DIABLO,
            TIPO_DRAGON,
			TIPO_PROYECTIL_DER,
			TIPO_PROYECTIL_IZQ,
			TIPO_NIEVE,
            TIPO_FUEGO,
			TIPO_NULL,
			TIPO_PARED_IZQUIERDA,
			TIPO_PARED_DERECHA,
			TIPO_PISO,
			TIPO_TECHO,
            TIPO_BONUS_VIDA,
            TIPO_BONUS_VELOCIDAD,                    
            TIPO_BONUS_NIEVE_LEJOS,
            TIPO_BONUS_NIEVE_POTENTE,
			//TIPO_BONUS_HABILITADO,
			//TIPO_BONUS_DESHABILITADO,
			TIPO_BONUS_LEVANTADO
					};

#define LADOS_TRIANGULO 3
#define LADOS_CUADRADO 4
#define LADOS_PENTAGONO 5
#define LADOS_HEXAGONO 6
#define LADOS_PARALELOGRAMO 4
#define LADOS_TRAPECIO 4
#define MAX_LADOS 6 // El poligono de mayor lados

// Defaults
#define PATH_ESCENARIO_DEFAULT "config\\escenario_default.json"
#define EXTENSION ".json"
#define IMAGEN_FONDO_DEFAULT "imagenes/fondoDefault.png"

#define FPS 30

#define ALTO_DEFAULT_PX 600
#define ANCHO_DEFAULT_PX 800
#define ALTO_DEFAULT_UL 100
#define ANCHO_DEFAULT_UL 100


//Simulacion del paso del tiempo Box2D
const float PASO_TIEMPO = 1.0f / 100.0f;

const int ITERACION_VELOCIDAD = 8;
const int ITERACION_POSICION = 8;

//gravedad del mundo Box2D
const float GRAVEDAD_X = 0.0f;
const float GRAVEDAD_Y = -9.80f;

const float FRICCION = 0.2f;
const float RESTITUCION = 0.2f;

// vertices de la figuras
static const int CANTIDADVERTICES = 4;

//Eventos recibidos por la vista/cliente
enum EVENTOS_RECIBIDOS_CLIENTE { 
					EVENTO_CLIENTE_JUEGO_RESET = 0,
					EVENTO_CLIENTE_JUEGO_SALIR,
					EVENTO_CLIENTE_JUEGO_PAUSA,
					EVENTO_CLIENTE_JUEGO_STEP,
					EVENTO_CLIENTE_FIGURA_ACTUALIZAR,
					EVENTO_CLIENTE_PERSONAJE_NUEVO_ID,
					EVENTO_CLIENTE_PERSONAJE_CREADO, 
					EVENTO_CLIENTE_PERSONAJE_QUIETO, 
					EVENTO_CLIENTE_PERSONAJE_QUIETO_IZQ,
					EVENTO_CLIENTE_PERSONAJE_QUIETO_DER,
					//EVENTO_CLIENTE_PERSONAJE_CAMINANDO, 
					EVENTO_CLIENTE_PERSONAJE_CAMINANDO_IZQ,
					EVENTO_CLIENTE_PERSONAJE_CAMINANDO_DER,

					EVENTO_CLIENTE_PERSONAJE_SALTANDO, 
					EVENTO_CLIENTE_PERSONAJE_SALTANDO_IZQ, 
					EVENTO_CLIENTE_PERSONAJE_SALTANDO_DER,
 
					EVENTO_CLIENTE_FIGURA_MURIENDO,
					EVENTO_CLIENTE_FIGURA_MUERTO,
					EVENTO_CLIENTE_PERSONAJE_DESCONECTADO,
					EVENTO_CLIENTE_PERSONAJE_LANZANDO,
					EVENTO_CLIENTE_PERSONAJE_EMPUJANDO,

					EVENTO_CLIENTE_CONEXION_ACEPTADA,
					EVENTO_CLIENTE_RECONEXION_ACEPTADA,
					EVENTO_CLIENTE_CONEXION_RECHAZADA_SALA_LLENA,
					EVENTO_CLIENTE_CONEXION_RECHAZADA_NOMBRE_EXISTENTE,
					EVENTO_CLIENTE_NULL,

					EVENTO_CLIENTE_ENEMIGO_CON_NIEVE_1,
					EVENTO_CLIENTE_ENEMIGO_CON_NIEVE_2,
					EVENTO_CLIENTE_ENEMIGO_BOLA_DE_NIEVE,

					EVENTO_CLIENTE_ENEMIGO_BOLA_DE_NIEVE_PATEADA,

					//Esto con IZQ solo para probarlo, despues se puede hacerlo con el flip
					EVENTO_CLIENTE_NIEVE_IZQ,

					EVENTO_CLIENTE_PROYECTIL_IZQ,
					EVENTO_CLIENTE_PROYECTIL_DER,

					EVENTO_CLIENTE_SNOWBOY_ATRAPADO_EN_BOLA_DE_NIEVE,
					EVENTO_CLIENTE_SNOWBOY_INVENCIBLE,
					EVENTO_CLIENTE_PERSONAJE_CORRIENDO_DER,
					EVENTO_CLIENTE_PERSONAJE_CORRIENDO_IZQ,
					EVENTO_CLIENTE_PERSONAJE_CORRIENDO_QUIETO_DER,
					EVENTO_CLIENTE_PERSONAJE_CORRIENDO_QUIETO_IZQ,

					EVENTO_CLIENTE_SNOWBOY_PUNTAJE_Y_VIDAS,

					EVENTO_CLIENTE_SNOWBOY_VA_A_RENACER,


					//TIPO_BONUS_HABILITADO,
					//TIPO_BONUS_DESHABILITADO,
					EVENTO_CLIENTE_BONUS_HABILITADO,
					EVENTO_CLIENTE_BONUS_DESHABILITADO,




					EVENTO_ESCENARIO_NIVEL_COMPLETADO,
					EVENTO_ESCENARIO_JUEGO_COMPLETADO,
					EVENTO_ESCENARIO_NUEVO_ESCENARIO,
					EVENTO_ESCENARIO_GAME_OVER



					};

//Eventos recibidos por juegoControlador/servidor
enum EVENTOS_RECIBIDOS_SERVIDOR { 
	                    EVENTO_SERVIDOR_SALIR = 0,
						EVENTO_SERVIDOR_PAUSA,
						EVENTO_SERVIDOR_RESET,

                        EVENTO_SERVIDOR_SALTAR_PERSONAJE,
                        EVENTO_SERVIDOR_MOVER_IZQ_PERSONAJE,
                        EVENTO_SERVIDOR_MOVER_DER_PERSONAJE,
											
						EVENTO_SERVIDOR_FRENAR_DER_PERSONAJE,
						EVENTO_SERVIDOR_FRENAR_IZQ_PERSONAJE,

						EVENTO_SERVIDOR_CREAR_SNOWBOY,
						EVENTO_SERVIDOR_MATAR_FIGURA,
						EVENTO_SERVIDOR_NULL,

						EVENTO_SERVIDOR_SNOWBOY_LANZAR_NIEVE
					};

//SnowBoy
#define MAX_VIDAS 4

#define SNOWBOY_ESCALA 1.2 

#define SNOWBOY_ALTO_PX 30
#define SNOWBOY_ANCHO_PX 20


#define RADIO_CUERPO  (1.3f*SNOWBOY_ESCALA)

#define SNOWBOY_FLOTACION_DESEADA (RADIO_CUERPO*2)//1.05F 

#define ALTURA_INICIAL_PIERNAS 0//(RADIO_CUERPO/-2)//-0.5f
#define ALTURA_FINAL_PIERNAS (-SNOWBOY_FLOTACION_DESEADA/*-0.5*/)//-2.0f
#define ANCHO_PIERNAS (RADIO_CUERPO/4)

#define ANGULO_MAX_ESCALABLE 55

#define RAYO_HORIZONTAL_POSX (RADIO_CUERPO+0.3f)
#define RAYO_HORIZONTAL_POSY 0

#define VELOCIDAD_HORIZONTAL 10
#define VELOCIDAD_HORIZONTAL_BONUS 15
#define VELOCIDAD_SALTO 10
#define SNOWBOY_CONSTANTE_DESACELERACION 0.25

#define SNOWBOY_ALTO_UL (SNOWBOY_FLOTACION_DESEADA+RADIO_CUERPO)
#define SNOWBOY_ANCHO_UL (RADIO_CUERPO*2)
#define PERSONAJE_SALTAR_UL (SNOWBOY_ALTO_UL)

#define SNOWBOY_DIFERENCIA_CENTRO_CUERPO_CENTRO_FIGURA (SNOWBOY_FLOTACION_DESEADA-SNOWBOY_ALTO_UL/2)

#define SNOWBOY_STEPS_PARA_RENACER 100


#define PERSONAJE_VISTA_CLIP_COUNT 3
//Constantes del Zoom
#define SNOWBOY_PROPORCION_SCROLL_X_EN_PANTALLA_MIN 0.25f //Al scrollear el SnowBoy va a estar en 1/2 de la pantalla desde la izq. Si fuera 0.25f estaria en 1/4 de la pantalla desde la izq
#define SNOWBOY_PROPORCION_SCROLL_Y_EN_PANTALLA 0.75f //Al scrollear el SnowBoy va a estar en 3/4 de la pantalla desde arriba. Si fuera .025f estaria en 1/4 de la pantalla desde arriba   
#define ZOOM_INICIAL 1.0f//1.5f
#define ZOOM_MAXIMO 4.1f
#define ZOOM_VARIACION 0.1f





enum bitsDeColision {
	BITS_ESCENARIO =			0x0001,
	BITS_SNOWBOY =				0x0002,
	BITS_NIEVE =				0x0004,
	BITS_ENEMIGO=				0x0008,
	BITS_ENEMIGO_CON_NIEVE =	0x0010,
	BITS_BOLA_DE_NIEVE_QUIETA =	0x0020,
	BITS_BOLA_DE_NIEVE_PATEADA=	0x0040,
    BITS_FUEGO =				0x0080,
	BITS_BONO =					0X0100,
};

#define DRAGON_TIEMPO_LANZAR_FUEGO 4000
#define DRAGON_TIEMPO_VIDA_FUEGO 140






#endif